### ISSUE TITLE
Avoid variadic `listen` with fastify 4

### ISSUE THREAD

**Issue by SimenB** [remcohaszing/axios-test-instance#6]
Using `fastify@4` with this module prints

```
(node:76172) [FSTDEP011] FastifyDeprecation: Variadic listen method is deprecated. Please use ".listen(optionsObject)" instead. The variadic signature will be removed in `fastify@5`.
    at Object.emit (/Users/simen/repos/monorepo/node_modules/process-warning/index.js:52:13)
    at Object.listen (/Users/simen/repos/monorepo/node_modules/fastify/lib/server.js:31:16)
    at /Users/simen/repos/monorepo/node_modules/axios-test-instance/index.js:29:17
    at new Promise (<anonymous>)
    at startServer (/Users/simen/repos/monorepo/node_modules/axios-test-instance/index.js:28:16)
    at patchInstance (/Users/simen/repos/monorepo/node_modules/axios-test-instance/index.js:90:34)
    at createInstance (/Users/simen/repos/monorepo/node_modules/axios-test-instance/index.js:126:28)
```

**Comment by remcohaszing** [comment]
This was released in version 6.0.0 :tada:
